# Change these first
owner: Liquid369 # Your GitHub organization or username, where this repository lives
repo: FlitsUptime # The name of this repository

sites:
  - name: FLS
    url: https://fls.flitswallet.app/api
    icon: https://api3.flitsnode.app/coins/fls.png
    method: GET
  - name: KTS
    url: https://kts.flitswallet.app/api
    icon: https://api3.flitsnode.app/coins/kts.png
    method: GET
  - name: DOGEC
    url: https://dogec.flitswallet.app/api
    icon: https://api3.flitsnode.app/coins/dogec.png
    method: GET
  - name: SCC
    url: https://scc.flitswallet.app/api
    icon: https://api3.flitsnode.app/coins/scc.png
    method: GET

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: liquid369.wtf
  # baseUrl: /your-repo-name
  logoUrl: https://api3.flitsnode.app/coins/fls.png
  favicon: https://api3.flitsnode.app/coins/fls.png
  name: Flits Uptime
  introTitle: "**Flits Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub and Upptime.js."
  introMessage: This is a starting status page which uses **real-time** data from our [GitHub repository](https://github.com/Liquid369/FlitsUptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: ZenDesk
      href: https://flits.zendesk.com/agent/dashboard
    - title: ASE
      href: https://ase.flitswallet.app
    - title: Cloud
      href: https://cloud.liquid369.xyz
  theme: dark
i18n:
    footer: This site is powered by [Liquid369](https://liquid369.dev)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
