# Change these first

owner: Liquid369 # Your GitHub organization or username, where this repository lives

repo: FlitsUptime # The name of this repository






  theme: dark

i18n:

    footer: This site is powered by [Liquid369](https://liquid369.dev)




# Upptime also supports notifications, assigning issues, and more

# See https://upptime.js.org/docs/configuration
